[package]
name = "tool"
authors = ["Corey Ryan <corey@coreyr.com>"]
description = ""
version = "0.1.0"
rust-version = "1.78"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "test_client"
path = "src/bin/test_client.rs"

[[bin]]
name = "simple_test"
path = "src/bin/simple_test.rs"

[dependencies]
anyhow = "1"
spin-sdk = "3.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[workspace]
