[package]
name = "coretools"
authors = ["Corey Ryan <corey@coreyr.com>"]
description = "MCP server for core computational tools"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
ftl-sdk = { version = "0.2.3", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = "0.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
spin-sdk = "4.0"

[features]
default = ["distance"]
distance = []
bearing = []
dot_product = []

[workspace]
members = []
exclude = ["server", "tools/geospatial/distance", "tools/geospatial/bearing", "tools/math3d/dot_product", "tools/geospatial/polygon_area", "tools/geospatial/point_in_polygon", "tools/geospatial/coordinate_conversion", "tools/math3d/cross_product", "tools/math3d/vector_magnitude", "tools/math3d/line_intersection", "tools/geospatial/buffer_polygon", "tools/geospatial/proximity_search", "tools/geospatial/proximity_zone", "tools/basic_math/add", "tools/basic_math/multiply", "tools/basic_math/square", "tools/basic_math/sqrt", "tools/basic_math/pythagorean", "tools/basic_math/distance_2d", "tools/math3d/line_plane_intersection", "tools/math3d/plane_plane_intersection", "tools/math3d/point_plane_distance", "tools/math3d/rotation_matrix", "tools/math3d/arbitrary_rotation", "tools/math3d/quaternion_from_axis_angle", "tools/math3d/quaternion_multiply", "tools/math3d/quaternion_slerp", "tools/math3d/matrix_vector_multiply", "tools/math3d/coordinate_conversion", "tools/math3d/tetrahedron_volume", "tools/math3d/sphere_volume", "tools/math3d/cylinder_volume", "tools/math3d/aabb_volume", "tools/math3d/pyramid_volume", "tools/math3d/sphere_ray_intersection", "tools/math3d/sphere_sphere_intersection", "tools/math3d/cylinder_ray_intersection", "tools/math3d/ray_aabb_intersection", "tools/math3d/point_line_distance", "tools/statistics/descriptive_statistics"]
