spin_manifest_version = 2

[application]
name = "coretools"
version = "0.1.0"
authors = ["Corey Ryan <corey@coreyr.com>"]
description = "Core computational tools MCP server"

[variables]
# List all tool components that should be discovered by the gateway
# Each component hosts exactly one tool due to WASM constraints
tool_components = { default = "distance,bearing,dot-product,polygon-area,point-in-polygon,coordinate-conversion" }

[[trigger.http]]
route = "/mcp"
component = "ftl-mcp-gateway"

[component.ftl-mcp-gateway]
source = { registry = "ghcr.io", package = "fastertools:ftl-mcp-gateway", version = "0.0.3" }
allowed_outbound_hosts = ["http://*.spin.internal"]
[component.ftl-mcp-gateway.variables]
tool_components = "{{ tool_components }}"
validate_arguments = "true"

[[trigger.http]]
route = "/distance"
component = "distance"

[component.distance]
source = "tools/geospatial/distance/target/wasm32-wasip1/release/distance_tool.wasm"
allowed_outbound_hosts = []
[component.distance.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "tools/geospatial/distance"
watch = ["tools/geospatial/distance/src/**/*.rs", "tools/geospatial/distance/Cargo.toml"]

[[trigger.http]]
route = "/bearing"
component = "bearing"

[component.bearing]
source = "tools/geospatial/bearing/target/wasm32-wasip1/release/bearing_tool.wasm"
allowed_outbound_hosts = []
[component.bearing.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "tools/geospatial/bearing"
watch = ["tools/geospatial/bearing/src/**/*.rs", "tools/geospatial/bearing/Cargo.toml"]

[[trigger.http]]
route = "/dot-product"
component = "dot-product"

[component.dot-product]
source = "tools/math3d/dot_product/target/wasm32-wasip1/release/dot_product_tool.wasm"
allowed_outbound_hosts = []
[component.dot-product.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "tools/math3d/dot_product"
watch = ["tools/math3d/dot_product/src/**/*.rs", "tools/math3d/dot_product/Cargo.toml"]

[[trigger.http]]
route = "/polygon-area"
component = "polygon-area"

[component.polygon-area]
source = "tools/geospatial/polygon_area/target/wasm32-wasip1/release/polygon_area_tool.wasm"
allowed_outbound_hosts = []
[component.polygon-area.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "tools/geospatial/polygon_area"
watch = ["tools/geospatial/polygon_area/src/**/*.rs", "tools/geospatial/polygon_area/Cargo.toml"]

[[trigger.http]]
route = "/point-in-polygon"
component = "point-in-polygon"

[component.point-in-polygon]
source = "tools/geospatial/point_in_polygon/target/wasm32-wasip1/release/point_in_polygon_tool.wasm"
allowed_outbound_hosts = []
[component.point-in-polygon.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "tools/geospatial/point_in_polygon"
watch = ["tools/geospatial/point_in_polygon/src/**/*.rs", "tools/geospatial/point_in_polygon/Cargo.toml"]

[[trigger.http]]
route = "/coordinate-conversion"
component = "coordinate-conversion"

[component.coordinate-conversion]
source = "tools/geospatial/coordinate_conversion/target/wasm32-wasip1/release/coordinate_conversion_tool.wasm"
allowed_outbound_hosts = []
[component.coordinate-conversion.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "tools/geospatial/coordinate_conversion"
watch = ["tools/geospatial/coordinate_conversion/src/**/*.rs", "tools/geospatial/coordinate_conversion/Cargo.toml"]


