spin_manifest_version = 2

[application]
name = "coretools"
version = "0.1.0"
authors = ["Corey Ryan <corey@coreyr.com>"]
description = "Core computational tools MCP server"

[variables]
# List all tool components that should be discovered by the gateway
# Each component hosts exactly one tool due to WASM constraints
tool_components = { default = "distance-two-d" }

[[trigger.http]]
route = "/mcp"
component = "ftl-mcp-gateway"

[component.ftl-mcp-gateway]
source = { registry = "ghcr.io", package = "fastertools:ftl-mcp-gateway", version = "0.0.3" }
allowed_outbound_hosts = ["http://*.spin.internal"]
[component.ftl-mcp-gateway.variables]
tool_components = "{{ tool_components }}"
validate_arguments = "true"

[[trigger.http]]
route = "/math"
component = ""

[component.distance-two-d]
source = "/Users/coreyryan/data/mashh/core-tools/tools/categories/basic_math"
allowed_outbound_hosts = ["http://pythagorean.spin.internal"]
[component.distance-two-d.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "tools/basic_math/distance_2d"
watch = ["tools/basic_math/distance_2d/src/**/*.rs", "tools/basic_math/distance_2d/Cargo.toml"]